backend:
  name: github
  repo: dongetikdigital/dongetik
  branch: main
  base_url: https://dongetik-oauth.dongetikdigital.workers.dev   # URL Worker Anda
  auth_endpoint: /auth   # Endpoint untuk login

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Artikel Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }
      - { label: "Gambar Sampul", name: "image", widget: "image", required: false }
